[[PYTHIA]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1aec8b9b210c563e75318c0d7598c142500d92f9"
libc = "glibc"
os = "linux"

    [[PYTHIA.download]]
    sha256 = "678f4d27b6db4ab280e0523ad9607f94414b8892c410b5efdc2b05d84c988d0b"
    url = "https://github.com/JuliaBinaryWrappers/PYTHIA_jll.jl/releases/download/PYTHIA-v8.309.0+0/PYTHIA.v8.309.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PYTHIA]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d92a36876d0bedfe3a0bb18637baeb44ebe31f4e"
libc = "glibc"
os = "linux"

    [[PYTHIA.download]]
    sha256 = "a78c971279db68fd34cd13e8f0fb93bed0400fc8babd9d0b0e80dfde58080c91"
    url = "https://github.com/JuliaBinaryWrappers/PYTHIA_jll.jl/releases/download/PYTHIA-v8.309.0+0/PYTHIA.v8.309.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PYTHIA]]
arch = "x86_64"
git-tree-sha1 = "38f79925e42e68238a96480c2810bcb5efefdebf"
os = "macos"

    [[PYTHIA.download]]
    sha256 = "f9e5dc1a0e35e06f2d8859e099801881a2faf736082507aed38f5791f4430ea1"
    url = "https://github.com/JuliaBinaryWrappers/PYTHIA_jll.jl/releases/download/PYTHIA-v8.309.0+0/PYTHIA.v8.309.0.x86_64-apple-darwin.tar.gz"
[[PYTHIA]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de28c18cba9e43e755e572514bf29d3f2b488b61"
libc = "glibc"
os = "linux"

    [[PYTHIA.download]]
    sha256 = "06532402b9424a3c2c90942595798b3e85f026f11dcafe097030412498a7cc8b"
    url = "https://github.com/JuliaBinaryWrappers/PYTHIA_jll.jl/releases/download/PYTHIA-v8.309.0+0/PYTHIA.v8.309.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PYTHIA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0dbff4b3c73998657abde11d51490c0dc9bcf0"
libc = "glibc"
os = "linux"

    [[PYTHIA.download]]
    sha256 = "b53573e9ede59aad8b4fab8a9b66240cc7257ac1ab3247580e52f03c2afa78e7"
    url = "https://github.com/JuliaBinaryWrappers/PYTHIA_jll.jl/releases/download/PYTHIA-v8.309.0+0/PYTHIA.v8.309.0.x86_64-linux-gnu-cxx11.tar.gz"
