# Autogenerated wrapper script for PYTHIA_jll for armv6l-linux-gnueabihf-cxx11
export libpythia8

JLLWrappers.@generate_wrapper_header("PYTHIA")
JLLWrappers.@declare_library_product(libpythia8, "libpythia8.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpythia8,
        "lib/libpythia8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
